### ISSUE TITLE
remove copied meanings in [ ] from top entry view

### ISSUE THREAD

**Issue by IrenH** [clld/csd#13]
this concerns the "pretty" view above the map. Would it be possible to not display all copied meanings (i.e. those in [...]) here, but to retain them in the table underneath the map? all meanings which are not copies from the gloss, so those without [..] should however remain.

**Comment by xrotwang** [comment]
e.g. http://csd.clld.org/parameters/1179#4/39.64/-94.44

**Comment by IrenH** [comment]
perfect
