### ISSUE TITLE
entries which only have \..cm are not shown on the website

### ISSUE THREAD

**Issue by IrenH** [clld/csd#14]
for entries which only have \..cm but no \(langauge) or \..oo : would it be possible to still list the \..cm?

**Comment by xrotwang** [comment]
But what would this comment be commenting if there is no word form whatsoever? I think it would be more transparent to incorporate such comments in the general comment for the entry, which lists language specific stuff very often (i.e. \com).

**Comment by IrenH** [comment]
not if the comments says something like "same as OP form"

**Comment by xrotwang** [comment]
well, but such a comment should just be replaced with a copy of OP form in the appropriate field, right?

**Comment by IrenH** [comment]
but they didn't do this.. i just had one such case and i copied over the form, but I have no idea whether there are other cases :(

**Comment by xrotwang** [comment]
I just ran a short test, and identified exactly one case where \cm was given but no form, \cm was *as in OP*. So I guess, we should just fix this case.

**Comment by IrenH** [comment]
ok, thanks I did :)
