### ISSUE TITLE
remove " " from pretty view

### ISSUE THREAD

**Issue by IrenH** [clld/csd#23]

**Comment by xrotwang** [comment]
example?

**Comment by IrenH** [comment]
looks to me like all Phonetic SIouan forms, those with the dagger are listed in " ", this is not necessary, since we are keeping the dagger after all

**Comment by xrotwang** [comment]
Do you have a link to an example?

**Comment by IrenH** [comment]
listed above, does it not work?

**Comment by xrotwang** [comment]
don't see anything to click on.

**Comment by IrenH** [comment]
again, Dakota:

http://csd.clld.org/parameters/903#4/41.64/-96.87

**Comment by IrenH** [comment]
I updated the comment, maybe you need to refresh your browser?

**Comment by IrenH** [comment]
insert comma between cognate and phonetic siouan and remove " " :)
