### ISSUE TITLE
sources: author and title seem to have gotten mixed up

### ISSUE THREAD

**Issue by IrenH** [clld/csd#24]
e.g. ASG, why is the authors name in the Title column?

could the columns Title and Author be switched, so that author is listed first? author is more important, as this column also lists native speakers

**Comment by IrenH** [comment]
also: capital letters throughout all abbreviations would be good, e.g.Mmi, pje

**Comment by xrotwang** [comment]
all uppercase even for names like *Lipkind*? If so, this would be easy to do.

**Comment by IrenH** [comment]
No just like in the ecxel table for the abbreviations...

**Comment by IrenH** [comment]
all 2 and 3 character abbreviations, though there are also some that are longer :(
