### ISSUE TITLE
Keep original paragraph formatting in General Comments

### ISSUE THREAD

**Issue by IrenH** [clld/csd#5]
With the comments, it would help to keep the original paragraphs instead of mushing them all into one.  These different paragraphs were probably written at different times, possibly even by different people, and to some extent commenting on and even disagreeing with each other.  Putting them into one paragraph is apt to be confusing.

**Comment by xrotwang** [comment]
e.g. http://csd.clld.org/parameters/1179#4/39.64/-94.44

**Comment by IrenH** [comment]
much better!
